export const contactSchemas = {
  Contact: {
    type: 'object',
    properties: {
      _id: { type: 'string' },
      label: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      address: { type: 'string' },
      city: { type: 'string' },
      state: { type: 'string' },
      country: { type: 'string' },
      zipCode: { type: 'string' },
      website: { type: 'string' },
      linkedin: { type: 'string' },
      github: { type: 'string' },
      twitter: { type: 'string' },
      instagram: { type: 'string' },
      facebook: { type: 'string' },
      youtube: { type: 'string' },
      availability: { type: 'string' },
      timezone: { type: 'string' },
      isActive: { type: 'boolean' },
      isDeleted: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
};
